/**
 * scripts/fetch-data.mjs — refresh the bundled historical real-return data.
 *
 * Builds annual REAL (inflation-adjusted) total returns for a stock sleeve and a bond
 * sleeve, which the Monte Carlo bootstraps:
 *   stock : ^SP500TR  (S&P 500 Total Return, dividends reinvested)   — Yahoo Finance
 *   bond  : VBMFX     (Vanguard Total Bond Market, total return)     — Yahoo Finance
 *   CPI   : CPIAUCSL  (US CPI, all urban consumers)                  — FRED (no key)
 *
 * realReturn = (1 + nominal) / (1 + inflation) − 1.  DEV/BUILD ONLY — the app never
 * touches the network at runtime. Run:  node scripts/fetch-data.mjs   (Node 18+).
 *
 * Note: this is a US developed-market stock/bond history (~late-1980s on). It is the
 * canonical data for this kind of simulation; longer history (1928+, incl. the 1970s
 * stagflation sequence) and China/Korea series are documented data upgrades.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'data.js');
const UA = { 'User-Agent': 'Mozilla/5.0 (longevity-compass data refresh)' };
const round4 = (x) => Math.round(x * 1e4) / 1e4;

// Year-end value per calendar year from a Yahoo monthly series (adjusted close = total return).
async function yahooYearEnd(sym) {
  const now = Math.floor(Date.now() / 1000);
  const u = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym)}?period1=0&period2=${now}&interval=1mo`;
  const r = await fetch(u, { headers: UA });
  if (!r.ok) throw new Error(`${sym} HTTP ${r.status}`);
  const j = await r.json();
  const res = j.chart && j.chart.result && j.chart.result[0];
  if (!res || !res.timestamp) throw new Error(`${sym}: no data`);
  const adj = (res.indicators.adjclose && res.indicators.adjclose[0].adjclose) || res.indicators.quote[0].close;
  const gmt = (res.meta && res.meta.gmtoffset) || 0;
  const yearEnd = {};
  for (let i = 0; i < res.timestamp.length; i++) {
    const c = adj[i];
    if (c == null || !isFinite(c)) continue;
    const y = new Date((res.timestamp[i] + gmt) * 1000).getUTCFullYear();
    yearEnd[y] = c; // chronological → ends as the last available month of year y
  }
  return yearEnd;
}

// Year-end CPI index per year from FRED CSV.
async function fredYearEnd(series) {
  const r = await fetch(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${series}`, { headers: UA });
  if (!r.ok) throw new Error(`FRED ${series} HTTP ${r.status}`);
  const txt = await r.text();
  const yearEnd = {};
  for (const line of txt.trim().split('\n').slice(1)) {
    const [date, val] = line.split(',');
    if (!date || val == null || val === '.' || val === '') continue;
    const v = parseFloat(val);
    if (!isFinite(v)) continue;
    yearEnd[+date.slice(0, 4)] = v;
  }
  return yearEnd;
}

console.log('  fetching ^SP500TR, VBMFX, CPIAUCSL ...');
const [spx, bnd, cpi] = await Promise.all([yahooYearEnd('^SP500TR'), yahooYearEnd('VBMFX'), fredYearEnd('CPIAUCSL')]);

const nowY = new Date().getUTCFullYear();
const years = [], stockReal = [], bondReal = [];
const candidate = Object.keys(spx).map(Number).sort((a, b) => a - b);
for (const y of candidate) {
  if (y >= nowY) continue; // skip the incomplete current year
  if (spx[y - 1] == null || bnd[y] == null || bnd[y - 1] == null || cpi[y] == null || cpi[y - 1] == null) continue;
  const sN = spx[y] / spx[y - 1] - 1;
  const bN = bnd[y] / bnd[y - 1] - 1;
  const inf = cpi[y] / cpi[y - 1] - 1;
  years.push(y);
  stockReal.push(round4((1 + sN) / (1 + inf) - 1));
  bondReal.push(round4((1 + bN) / (1 + inf) - 1));
}

if (years.length < 20) { console.error(`\nOnly ${years.length} aligned years — aborting, data.js unchanged.`); process.exit(1); }

const gm = (a) => Math.pow(a.reduce((p, r) => p * (1 + r), 1), 1 / a.length) - 1;
const out = {
  source: 'Yahoo Finance (^SP500TR, VBMFX) + FRED (CPIAUCSL)',
  note: 'Annual REAL total returns (inflation-adjusted, dividends reinvested).',
  generated: new Date().toISOString().slice(0, 10),
  from: years[0], to: years[years.length - 1],
  years, stockReal, bondReal
};
const banner = `/* AUTO-GENERATED by scripts/fetch-data.mjs — do not edit by hand.\n`
  + ` * ${out.source}\n * ${out.note}  ${out.from}–${out.to}. Refresh: npm run fetch-data */\n`;
writeFileSync(OUT, banner
  + `(function(root){var D=${JSON.stringify(out)};`
  + `if(typeof module==='object'&&module.exports)module.exports=D;else root.LC_DATA=D;`
  + `})(typeof self!=='undefined'?self:this);\n`);

console.log(`  wrote ${years.length} yrs (${out.from}–${out.to})  |  real CAGR: stock ${(gm(stockReal) * 100).toFixed(1)}%, bond ${(gm(bondReal) * 100).toFixed(1)}%`);
